### ISSUE TITLE
Rarely use location dependent styles

### ISSUE THREAD

**Issue by austinstarin** [punkave/best-practices#44]
Recapping our discussion here from last week...

**"Rarely use location dependent styles".** This ensures that selectors can be reused anywhere and are context agnostic. This also maintains orthogonality and reduces managing cascade across multiple files.

A core aspect of object oriented CSS  is "separation of container from content", which is outlined here in Nicole's outline https://github.com/stubbornella/oocss/wiki#separate-container-and-content.

ITCSS follows many OOCSS principles and Harry's thesis argues that the cascade and specificity cause issues in CSS projects at scale. You may struggle with naming these contextual scenarios or where to put them in your less folders because ITCSS doesn't account for them.

```less
// Using cascade
.context {
  .aside {
    padding-bottom: 3rem;

    .title {
      padding-bottom: 4rem;
    }
  }
}
```

```less
// OOCSS
.context { ... }
.aside { ... }
.aside--context { padding-bottom: 3rem; }
.title { ... }
.title--context { padding-bottom: 4rem; }
```
