### ISSUE TITLE
Naming less color variables

### ISSUE THREAD

**Issue by austinstarin** [punkave/best-practices#8]
Consider naming a color variable in your `_colors.less` file or `_settings.less` file by role instead of color. This makes it easy to swap out colors across a UI if a color changes.

Instead of...

``` less
@red: #FF0000;

.foo {
  background-color: @red;
}
```

Consider...

``` less
@brand-primary: #FF0000;

.foo {
  background-color: @brand-primary;
}
```

You can also create aliases if it helps to remember color key/values...

``` less
@red: #FF0000;
@brand-primary: @red;

.foo {
  background-color: @brand-primary;
}
```
